
export const ACTION_MENU_COLLAPSE = 'ACTION_MENU_COLLAPSE';
export const ACTION_MENU_ITEM = 'ACTION_MENU_ITEM';
export const ACTION_MENU_SET_ITEMS = 'ACTION_MENU_SET_ITEMS';

export const ACTION_IS_AUTH = 'ACTION_IS_AUTH';
export const ACTION_SET_TOKEN = 'ACTION_SET_TOKEN';
export const ACTION_CHANGE_LOGIN_INPUT = 'ACTION_CHANGE_LOGIN_INPUT';
export const ACTION_CHANGE_PASSWORD_INPUT = 'ACTION_CHANGE_PASSWORD_INPUT';
export const ACTION_CHANGE_EMAIL_INPUT = 'ACTION_CHANGE_EMAIL_INPUT';

export const ACTION_CHANGE_SET_ALL_LIST = 'ACTION_CHANGE_SET_ALL_LIST';
export const ACTION_CHANGE_FILTER_NAME = 'ACTION_CHANGE_FILTER_NAME';